name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - 
        name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(echo $GITHUB_SHA | cut -c1-8)" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: macrosdockerhub/python-app:${{ env.sha_short }}