name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Declare SHA
        shell: bash
        run: |
          echo "sha_short=$(echo $GITHUB_SHA | cut -c1-8)" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: macrosdockerhub/python-app:${{ env.sha_short }}
  cd:
    needs: ci
    runs-on: self-hosted    
    steps:
      -
        name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          mv ./argocd /usr/local/bin/argocd
      -
        name: Sync with ArgoCD
        shell: bash
        run: |
          argocd login argocd-server.argocd --insecure --grpc-web \
          --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

